// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA16NuZe9jdmJ9BMQo_SHuVi5SMWk_3uH0',
    appId: '1:601901033214:web:41c5f715a7af582a3b67af',
    messagingSenderId: '601901033214',
    projectId: 'saahayak-77fed',
    authDomain: 'saahayak-77fed.firebaseapp.com',
    storageBucket: 'saahayak-77fed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMX7xCn8jqYTicQvQXKFeHXmWwYaXbw9E',
    appId: '1:601901033214:android:6640039881848a8d3b67af',
    messagingSenderId: '601901033214',
    projectId: 'saahayak-77fed',
    storageBucket: 'saahayak-77fed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwy-wAKtrTigWnq9lW0uLv6REeBmEwI8E',
    appId: '1:601901033214:ios:ea5da276764843833b67af',
    messagingSenderId: '601901033214',
    projectId: 'saahayak-77fed',
    storageBucket: 'saahayak-77fed.appspot.com',
    iosBundleId: 'com.example.sahayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwy-wAKtrTigWnq9lW0uLv6REeBmEwI8E',
    appId: '1:601901033214:ios:b2df1d1f2a29376b3b67af',
    messagingSenderId: '601901033214',
    projectId: 'saahayak-77fed',
    storageBucket: 'saahayak-77fed.appspot.com',
    iosBundleId: 'com.example.sahayak.RunnerTests',
  );
}
